### ISSUE TITLE
查看答案

### ISSUE THREAD

**Issue by Darmin5** [amtoaer/goqut#3]
输入ans之后并没有暂停，而是直接跳到下一个题目了😂

**Comment by amtoaer** [comment]
啊，确实，马上修！

**Comment by amtoaer** [comment]
[1.1.1版本](https://github.com/amtoaer/goqut/releases/tag/1.1.1)应该可以了

**Comment by Darmin5** [comment]
辛苦了hhh，我自己在我这边修好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amtoaer/goqut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amtoaer/goqut] 查看答案 (Issue #3)





 
1.1.1版本应该可以了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amtoaer** [comment]
233，感觉是 Golang 标准库的锅，在不同平台行为不一样
